name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.13.0]
    env:
       NEXT_WEBSITE_URL: ${{secrets.NEXT_WEBSITE_URL}}
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Change Directory and Restart PM2
    run: |
          cd /home/user/actions-runner/_work/averias-app/averias-app
          pm2 restart 0
